#!/bin/sh

#SERV_HOST_LIST="10.10.10.11 10.10.10.12 10.10.10.13"
SERV_HOST_LIST="10.10.10.14 10.10.10.15 10.10.10.16 10.10.10.17"

for serv_host in $SERV_HOST_LIST
do
   echo "================== kill server in $serv_host ==========================="
   sleep 2
   ssh $serv_host "killall -9 idgs-aio;killall -9 startup.sh;killall -9 tail"
   sleep 3
   echo
done

CLIENT_LIST="10.10.10.51"
for client in $CLIENT_LIST
do
  echo "================== kill client in $client =============================="
  sleep 2
  ssh $client "killall -9 idgs-aio;killall -9 tail;killall -9 load;killall -9 tpch_Q6;"
  sleep 3
done


for serv_host in $SERV_HOST_LIST
do
  scp $serv_host/cluster.conf root@$serv_host:/home/idgs/framework/conf/cluster.conf
  scp $serv_host/tpch-case.sh root@$serv_host:/home/idgs/build/tpch-case.sh
  ssh $serv_host "source /etc/profile;cd /home/idgs;./build/tpch-case.sh" &
  sleep 5
done



for client in $CLIENT_LIST
do
  echo "================== start client in $client =============================="
  sleep 2
  ssh $client "source /etc/profile;cd /home/tpch_pt;./cp_files;cd /home/idgs/;./build/tpch.sh"
  sleep 3
done

echo "==================== finish TPCH Q6 test =================================="

sleep 3

for serv_host in $SERV_HOST_LIST
do
   echo "================== kill server in $serv_host ==========================="
   sleep 2
   ssh $serv_host "killall -9 idgs-aio;killall -9 startup.sh;killall -9 tail"
   sleep 3
   echo
done

