#!/bin/sh

HOST_LIST="10.10.10.11 10.10.10.12 10.10.10.13 10.10.10.14 10.10.10.15 10.10.10.16 10.10.10.17 10.10.10.51"
#HOST_LIST="10.10.10.11 10.10.10.12 10.10.10.13 10.10.10.14 10.10.10.15 10.10.10.17 10.10.10.51"

#ssh -L 2401:10.10.10.91:2401 root@10.238.152.105
#rm -rf /home/idgs
#cd /home
#cvs co idgs

proxy_host=10.238.152.179
ssh $proxy_host "source /etc/profile;rm -rf /localdisk/idgs;cd /localdisk;cvs co idgs"
rm -rf /home/idgs
cd /home
scp -r $proxy_host:/localdisk/idgs .

echo "---------------------------------------------------------------"
echo " will update data on " $HOST_LIST 10.10.10.52
echo "---------------------------------------------------------------"

sleep 2

for host in $HOST_LIST
do
   echo "================== update code in $host ===========================" 
   ssh $host "source /etc/profile;cd /home/;rm -rf idgs/;alias cp='cp -f';"
   scp -r /home/idgs $host:/home/
   scp /home/pt_script/script $host:/home/idgs/
   scp /home/pt_script/make_file $host:/home/idgs/
   scp /home/pt_script/cicheck.sh $host:/home/idgs/
   echo
done

for host in $HOST_LIST
do
   echo "================== compile code in $host ==========================="
   sleep 2
   ssh $host "source /etc/profile;cd /home/idgs/;./make_file;" & 
done

echo "================== compile code in 10.10.10.52 ============================"
sleep 5
sh 10.10.10.52 "source /etc/profile;cd /home/idgs/;./make_file;"


echo "---------------------------------------------------------------"
echo " code is synched to " $HOST_LIST 10.10.10.52
echo "---------------------------------------------------------------"

