#!/bin/bash

# public address
idgs_member_ip=10.1.42.11

# public port
idgs_member_port=7700

# inner address
idgs_member_innerIp=10.1.42.11

# inner port
idgs_member_innerPort=8800

# worker thread pool
#idgs_thread_count=10

# IO thread pool
#idgs_io_thread_count=4

# idle thread may save energy.
#idgs_max_idle_thread=1

# MTU of UDP channel, MTU=0 means TCP only  
#idgs_mtu=0

# Innter TCP: batch recv/send messages count. Larger batch size, less system call.
#idgs_tcp_batch=200

# partition count, should be a primary integer, it is recommended to be <total CPU core> X 2
#idgs_partition_count=233

# whether local member store data.
#idgs_member_service_local_store=true

# GLOG related
#GLOG_v=0
