
/*
Copyright (c) <2013>, Intel Corporation All Rights Reserved.

The source code, information and material ("Material") contained herein is owned by Intel Corporation or its suppliers or licensors, and title to such Material remains with Intel Corporation or its suppliers or licensors. The Material contains proprietary information of Intel or its suppliers and licensors. The Material is protected by worldwide copyright laws and treaty provisions. No part of the Material may be used, copied, reproduced, modified, published, uploaded, posted, transmitted, distributed or disclosed in any way without Intel's prior express written permission. No license under any patent, copyright or other intellectual property rights in the Material is granted to or conferred upon you, either expressly, by implication, inducement, estoppel or otherwise. Any license under such intellectual property rights must be express and approved by Intel in writing.

Unless otherwise agreed by Intel in writing, you may not remove or alter this notice or any other notice embedded in Materials by Intel or Intel’s suppliers or licensors in any way.
*/
#if defined(__GNUC__) || defined(__clang__) 
#include "idgs_gch.h" 
#endif // GNUC_ $
#include "idgs/actor/actor_worker.h"
#include "idgs/actor/actor_message_queue.h"
#include "idgs/cluster/cluster_framework.h"


using namespace std;
using namespace idgs::pb;
using namespace idgs::net;

namespace idgs {
namespace actor {
void ActorWorker::start() {
  if (m_pthread == NULL) {
//        DVLOG(2)<<"Thread " << id << " is created ";
    m_pthread = new std::thread(std::bind(&ActorWorker::run, this));
  }
}

void ActorWorker::terminateAndJoin() {
  m_is_finish.fetch_and_store(true);
  this->join();
}

void ActorWorker::join() {
  if (m_pthread != NULL) {
    DVLOG(2) << "Thread " << id << " is joining ";
    ::idgs::util::singleton<ActorMessageQueue>::getInstance().notifyAll();
    m_pthread->join();
    delete m_pthread;
    m_pthread = NULL;
  }
}

void ActorWorker::processTcpOrietatedMessage(std::shared_ptr<ActorMessage>& msgPtr) {
  // Message is generated by TCP
  DVLOG(3) << "buffer size: " << msgPtr->getRpcBuffer()->getBodyLength() << ", content: "
              << dumpBinaryBuffer(
                  std::string(msgPtr->getRpcBuffer()->getBody(), msgPtr->getRpcBuffer()->getBodyLength()));
  msgPtr->parseRpcBuffer();

  RpcMessage* newmsg = msgPtr->getRpcMessage().get();
  DVLOG(2) << "TCP Actor '" << msgPtr->getTcpActorId() << "' got read message: " << newmsg->DebugString();
  DVLOG(2) << "Get Dest ActorID " << newmsg->dest_actor().actor_id();

  DLOG_IF(FATAL, newmsg->dest_actor().actor_id().empty()) << "Destination actor ID is empty: " << newmsg->DebugString();
  DLOG_IF(WARNING, newmsg->source_actor().actor_id().empty()) << "Source actor ID is empty: " << newmsg->DebugString();

  static int32_t localMemberId =
      ::idgs::util::singleton<idgs::cluster::ClusterFramework>::getInstance().getMemberManager()->getLocalMemberId();

  newmsg->mutable_client_actor()->set_actor_id(newmsg->source_actor().actor_id());
  newmsg->mutable_client_actor()->set_member_id(newmsg->source_actor().member_id());

  newmsg->mutable_source_actor()->set_actor_id(msgPtr->getTcpActorId());
  newmsg->mutable_source_actor()->set_member_id(localMemberId);

  DVLOG(2) << "Session get Actor Message: " << msgPtr->toString();

  /// destination is other member
  int32_t destMemberId = newmsg->dest_actor().member_id();

  if (destMemberId != localMemberId && destMemberId != ANY_MEMBER && destMemberId != ALL_MEMBERS) {
    static NetworkModel* network = ::idgs::util::singleton<RpcFramework>::getInstance().getNetwork();
    network->send(msgPtr);
    return;
  }

  localProcess(msgPtr);
}

void ActorWorker::processMessage(idgs::actor::ActorMessagePtr& msgPtr) {
  switch (msgPtr->getMessageOrietation()) {
  case ActorMessage::UDP_ORIENTED:
  case ActorMessage::INNER_TCP:
    msgPtr->parseRpcBuffer();
    localProcess(msgPtr);
    break;
  case ActorMessage::APP_ORIENTED:
    localProcess(msgPtr);
    break;
  case ActorMessage::OUTER_TCP:
    processTcpOrietatedMessage(msgPtr);
    break;
  default:
    LOG(ERROR)<< "unknown message orientation.";
  }
}

void ActorWorker::run() {
  set_thread_name("idgs_worker");

  idgs::actor::ActorMessageQueue& actor_queue = ::idgs::util::singleton<ActorMessageQueue>::getInstance();
  std::shared_ptr<ActorMessage> msgPtr;
  while (!m_is_finish.load()) {
    try {
      if (actor_queue.try_pop(&msgPtr)) {
        DVLOG(2) << "Thread " << id << " Got message " << msgPtr->getMessageOrietation() << ", content:"
                    << msgPtr->toString();
        processMessage(msgPtr);
        msgPtr.reset();
      } else {
        actor_queue.wait();
      }
    } catch (std::exception &e) {
      LOG(ERROR)<< "Got exception in worker thread, cause: " << e.what();
    } catch (...) {
      catchUnknownException();
    }
  }

  DVLOG(1) << "thread " << getId() << " exit.";
}

void ActorWorker::localProcess(std::shared_ptr<ActorMessage>& actorMsg) {
  DLOG_IF(ERROR, (actorMsg->getDestMemberId() == UNKNOWN_MEMBER || actorMsg->getSourceMemberId() == UNKNOWN_MEMBER))
                                                                                                                        << "Unknown member: "
                                                                                                                        << actorMsg->toString();

  if (actorMsg->getDestMemberId() == UNKNOWN_MEMBER || actorMsg->getSourceMemberId() == UNKNOWN_MEMBER) {
    return;
  }

  /// destination is local member.
  const string destActorId = actorMsg->getDestActorId();
  static ActorFramework* af = ::idgs::util::singleton<RpcFramework>::getInstance().getActorFramework();
  Actor* actor = af->getActor(destActorId);
  if (actor != NULL) {
    try {
      actor->process(actorMsg);
    } catch (std::exception& e) {
      LOG(ERROR)<< actor->getDescriptor()->getName() << ", error" << e.what();
    } catch (...) {
      LOG(ERROR) << actor->getDescriptor()->getName() << ", error";
      catchUnknownException();
    }
  } else {
    LOG(ERROR) << "Can not find any actor " << destActorId << " for message " << actorMsg->toString();
  }
}} // namespace actor
} // namespace idgs
