#!/bin/sh

SERV_HOST_LIST="10.10.10.14 10.10.10.15 10.10.10.16 10.10.10.17"
#SERV_HOST_LIST="10.10.10.14 10.10.10.15 10.10.10.17 "

for serv_host in $SERV_HOST_LIST
do
   echo "================== kill server in $serv_host ==========================="
   sleep 2
   ssh $serv_host "killall -9 idgs-aio;killall -9 startup.sh;killall -9 tail;killall -9 ssh"
   sleep 3
   echo
done
