#!/bin/sh

#SERV_HOST_LIST="HOST_LIST="10.10.10.14 10.10.10.15 10.10.10.16 10.10.10.17 "
SERV_HOST_LIST="HOST_LIST="10.10.10.14 10.10.10.15 10.10.10.17 "

for serv_host in $SERV_HOST_LIST
do
   echo "================== kill server in $serv_host ==========================="
   sleep 2
   ssh $serv_host "killall -9 idgs-aio;killall -9 startup.sh;killall -9 tail"
   sleep 3
   echo
done

CLIENT_LIST="10.10.10.51"
for client in $CLIENT_LIST
do
  echo "================== kill client in $client =============================="
  sleep 2
  ssh $client "killall -9 idgs-aio;killall -9 tail;killall -9 load;killall -9 source;killall -9 startup"
  sleep 3
done


for serv_host in $SERV_HOST_LIST
do
  scp $serv_host/cluster.conf root@$serv_host:/home/idgs/poc/sunrise/conf/cluster.conf
  ssh $serv_host "source /etc/profile;cd /home/idgs;./poc/sunrise/startup.sh" &
  sleep 10
done



for client in $CLIENT_LIST
do
  echo "================== start client in $client =============================="
  sleep 2
  scp client-conf/client.conf $client:/home/idgs/poc/sunrise/conf/client.conf
  scp client-conf/load.sh $client:/home/idgs/poc/sunrise/load.sh
  ssh $client "source /etc/profile;cd /home/idgs;./poc/sunrise/load.sh;./poc/sunrise/case1.sh"
  sleep 3
done

echo "==================== finish Sunrise test =================================="

sleep 3

for serv_host in $SERV_HOST_LIST
do
   echo "================== kill server in $serv_host ==========================="
   sleep 2
   ssh $serv_host "killall -9 idgs-aio;killall -9 startup.sh;killall -9 tail"
   sleep 3
   echo
done

for client in $CLIENT_LIST
do
  echo "================== kill client in $client =============================="
  sleep 2
  ssh $client "killall -9 source"
  sleep 3
done

